#!/bin/bash

set -o pipefail

echo Regression tests suit 
echo 'Number of Loops = ' $1
echo 'EmailResultsPerson = ' $2

status=PASS
for((i=1;i<=$1;i+=1));
do
echo 'Run test for ' $i 'time' 
./gradlew testRelease 2>&1 | tee output.log
if [ $? -ne 0 ]; then
    status=FAIL
    break
fi
done
echo All done

if [ "$2" != "" ]; then
    echo "Sending email to - " $2  
    
    python send_email.py $2 $status output.log

else
    echo "There is no EmailResultsPerson"
fi
